apiVersion: v1    
kind: PersistentVolume    
spec:    
  storageClassName: default    
  capacity:    
    storage: 5Gi    
  accessModes:    
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain 
