apiVersion: v1    
kind: PersistentVolumeClaim    
metadata:    
 name: lagopus-pvc
spec:    
 storageClassName: default    
 accessModes:    
   - ReadWriteMany
 resources:    
   requests:    
     storage: 1Gi  
